[project]
name = "hyprtheme"
version = "0.1.0"
description = "A cli to make hyprland theme change easy"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
]

[dependency-groups]
dev = [
    "ty>=0.0.1a18",
]

[project.scripts]
hyprot = "hyprtheme.cli"
